# Yazi Configuration - Rosé Pine themed

[mgr]
ratio          = [1, 3, 4]
preview_visible = true
mouse_events   = ["click", "scroll"]

[preview]
max_width  = 600
max_height = 900
image_filter = "auto"

[open]
rules = [
  { name = "image", mime = "image/*", use = ["feh", "--auto-zoom", "{}"] },
  { name = "video", mime = "video/*", use = ["mpv", "{}"] },
  { name = "audio", mime = "audio/*", use = ["mpv", "{}"] },
  { name = "pdf", mime = "application/pdf", use = ["zathura", "{}"] },
  { name = "text", mime = "text/*", use = ["$EDITOR", "{}"] },
]
